# config/twitter.yml

development:
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  access_secret: <%= ENV["TWITTER_ACCESS_SECRET"] %>

production:
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  access_secret: <%= ENV["TWITTER_ACCESS_SECRET"] %>
